[2024-02-22T15:10:30.753+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion.load_data manual__2024-02-22T15:10:26.767963+00:00 [queued]>
[2024-02-22T15:10:30.757+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion.load_data manual__2024-02-22T15:10:26.767963+00:00 [queued]>
[2024-02-22T15:10:30.758+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-02-22T15:10:30.762+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): load_data> on 2024-02-22 15:10:26.767963+00:00
[2024-02-22T15:10:30.766+0000] {standard_task_runner.py:57} INFO - Started process 8904 to run task
[2024-02-22T15:10:30.768+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion', 'load_data', 'manual__2024-02-22T15:10:26.767963+00:00', '--job-id', '397', '--raw', '--subdir', 'DAGS_FOLDER/fetch-api-data.py', '--cfg-path', '/tmp/tmpn6xd3izj']
[2024-02-22T15:10:30.770+0000] {standard_task_runner.py:85} INFO - Job 397: Subtask load_data
[2024-02-22T15:10:30.793+0000] {task_command.py:416} INFO - Running <TaskInstance: data_ingestion.load_data manual__2024-02-22T15:10:26.767963+00:00 [running]> on host 8ffe65393bc1
[2024-02-22T15:10:30.889+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-02-22T15:10:26.767963+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-22T15:10:26.767963+00:00'
[2024-02-22T15:10:30.893+0000] {base.py:73} INFO - Using connection ID '***_conn' for task execution.
[2024-02-22T15:10:30.893+0000] {logging_mixin.py:154} INFO - Error while connecting to PostgreSQL invalid dsn: missing "=" after "***,***," in connection info string
[2024-02-22T15:10:30.893+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-02-22T15:10:30.897+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_ingestion, task_id=load_data, execution_date=20240222T151026, start_date=20240222T151030, end_date=20240222T151030
[2024-02-22T15:10:30.945+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-02-22T15:10:30.953+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
