[2024-02-22T15:13:00.991+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion.load_data manual__2024-02-22T15:12:56.651621+00:00 [queued]>
[2024-02-22T15:13:00.995+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion.load_data manual__2024-02-22T15:12:56.651621+00:00 [queued]>
[2024-02-22T15:13:00.995+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-02-22T15:13:00.999+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): load_data> on 2024-02-22 15:12:56.651621+00:00
[2024-02-22T15:13:01.003+0000] {standard_task_runner.py:57} INFO - Started process 9000 to run task
[2024-02-22T15:13:01.005+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion', 'load_data', 'manual__2024-02-22T15:12:56.651621+00:00', '--job-id', '400', '--raw', '--subdir', 'DAGS_FOLDER/fetch-api-data.py', '--cfg-path', '/tmp/tmpkis2bnkb']
[2024-02-22T15:13:01.007+0000] {standard_task_runner.py:85} INFO - Job 400: Subtask load_data
[2024-02-22T15:13:01.030+0000] {task_command.py:416} INFO - Running <TaskInstance: data_ingestion.load_data manual__2024-02-22T15:12:56.651621+00:00 [running]> on host 8ffe65393bc1
[2024-02-22T15:13:01.107+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-02-22T15:12:56.651621+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-22T15:12:56.651621+00:00'
[2024-02-22T15:13:01.112+0000] {base.py:73} INFO - Using connection ID '***_conn' for task execution.
[2024-02-22T15:13:01.113+0000] {logging_mixin.py:154} INFO - Error while connecting to PostgreSQL invalid dsn: missing "=" after "***," in connection info string
[2024-02-22T15:13:01.113+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-02-22T15:13:01.116+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_ingestion, task_id=load_data, execution_date=20240222T151256, start_date=20240222T151300, end_date=20240222T151301
[2024-02-22T15:13:01.137+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-02-22T15:13:01.146+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
